### ISSUE TITLE
Geodata names

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/rt_vis#1]
The current geodata names and RT data names don't always align. 

i.e. `United States` vs. `United States of America`. Need to switch to the correct geodata with no name issues.

**Comment by seabbs** [comment]
Let me know if I can do anything to help resolve this. We can maybe output the ISO codes into the saved results (i.e into `reported_cases.csv` if that would help.

**Comment by hamishgibbs** [comment]
Handled by RtD3 which gives user easier control of geographic names. If a country is missing data in the visualisations but should have it, the names in the input geodata should be changed.

This is applicable to the case where rt estimates record "United States" and geodata records "United States of America". The names should be aligned in R before passing to RtD3 (and then to this library).

I support keeping the reliance on names as is (not adding iso codes) so that the same interface will work for subnational estimates.

**Comment by seabbs** [comment]
agree - sounds like the most flexible set up.

**Comment by hamishgibbs** [comment]
Sounds good. Closing.

**Comment by seabbs** [comment]
Good idea to flag this in the docs if not already done.

**Comment by hamishgibbs** [comment]
RtD3 could benefit from a validate_name_agreement function or similar to ensure that all names in the estimates are present in the geodata I think

**Comment by seabbs** [comment]
good idea

**Comment by seabbs** [comment]
you could do an `anti_join` and then warn if the resulting data frame is not zero rows.
