### ISSUE TITLE
Switch from country -> region

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#10]
For general usage, it might be better to switch to a more generic term. I've looked at changing this in `RtD3` and then mapping to what `rt_vis` expects but it might make more sense to make the change here.

**Comment by seabbs** [comment]
Can then also change `RtD3` to expect region as the input.

**Comment by hamishgibbs** [comment]
This has been changed so the default column names expected will be 'Region' (summaryData) and 'region' (rtData, casesInfectionData, casesReportData).

Changed in both rt_vis and RtD3.
