### ISSUE TITLE
time filters return to previous but estimates can be in the future

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#12]
The time filters at the bottom of the summary visualisation refer to the past (i.e previous) but the previous 7 days is actually a forecast.

**Comment by hamishgibbs** [comment]
Should be addressed by #16, but would like to check that the change was what you were thinking before closing @seabbs.

Now, when filtering time, no forecasts > `Date.now()` will appear unless viewing the whole time series.

**Comment by seabbs** [comment]
As discussed think probably better to reference based on the input data (or potentially an input date) as this may be used on historic estimates.

**Comment by hamishgibbs** [comment]
Just replaced the date filtering buttons with a time slider in their place. What do you think of the new approach?

Has cleaned up the internal workings a bit which I like. I believe there may be a bit more to do to let people know that it is an interactive slider but if someone ventures over it with their mouse it should be apparent.

#34.

**Comment by hamishgibbs** [comment]
This should be handled by the addition of the time slider.
