### ISSUE TITLE
Show by country summary information

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#14]
At the moment `summaryData` is passed in and used for mapping. it would be great if this could be shown in some way. A really nice way of doing this might be as a pop-up on the map but other approaches may exist that are better.

**Comment by hamishgibbs** [comment]
Would you like a tooltip or table? I like a tooltip on hover over countries

**Comment by seabbs** [comment]
agree.

**Comment by seabbs** [comment]
Only downside is that you won't have this if you don't have a map but not the end of the world.

**Comment by hamishgibbs** [comment]
Added with #32 and new choropleth maps for summaryData variables added with #33. Still need to discuss the best color scales for the maps but this should be in place now.
