### ISSUE TITLE
Clarify date slider

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/rt_vis#42]
Need to make it more clear that the date slider is a date slider. May be nice to have the colour palette of estimate/forecast etc. that responds to hover.

**Comment by hamishgibbs** [comment]
Doing this should also address #41

**Comment by hamishgibbs** [comment]
Doing away with date slider and adding the date brush to all available plots may be more clear

**Comment by seabbs** [comment]
Yes agree, though it may potentially be a bit less flexible... hmmm not 100% that just communicating what it is might not be better. Up to you though I am very undecided.
