### ISSUE TITLE
Map styling

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/rt_vis#50]
Clicking on deaths makes legend disappear and removes some styling. 

https://github.com/epiforecasts/RtD3/issues/35

**Comment by hamishgibbs** [comment]
@seabbs - looks like this is caused by null values in Papua New Guinea in `deaths/summary/summary_table.csv`. I will add a catch to handle it.

**Comment by seabbs** [comment]
Good find. I have no idea why those would occur though.... hmmm could you perhaps open an issue in `epiforecasts/covid-rt-estimates` highlighting what you have found and I'll get on it as it can't be a good sign!

**Comment by hamishgibbs** [comment]
Something is still wrong here. Reopening.
