### ISSUE TITLE
Filter left hand side broken

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#55]
In the latest version (which is now live on epiforecasts.io/covid if needing to check) looks like the date filter is broken on the left hand side? Do you see this as well @hamishgibbs?

**Comment by hamishgibbs** [comment]
Do you mean that the time series are still starting from the min date of the whole dataset - not that individual country?

**Comment by seabbs** [comment]
No sorry for being unclear. I mean that the filter control in the bottom right is not working when used to filter using the left hand side of the box.

**Comment by seabbs** [comment]
Global page seems fine but I see the issue on the UK page: https://epiforecasts.io/covid/posts/national/united-kingdom/

Hard to describe, might be easier to have a quick play with it.

**Comment by hamishgibbs** [comment]
From https://epiforecasts.io/covid/posts/global/ - I don't see any of the most recent changes from the newest `rt_vis` release (no header in the map legend, no date filtering title).

**Comment by hamishgibbs** [comment]
The newest changes are in place here: 

https://hamishgibbs.github.io/rt_vis/

Looks like the epiforecasts site is using an older rt_vis version? Is that correct?

**Comment by seabbs** [comment]
Global have missed the RtD3 update. Website was updated when we merged but the box may have been in the middle of an update and so only caught some of the pages (global is first in the list and UK is last so this would make sense). Changes will pop in from the next update. See the UK page for the issue.

**Comment by seabbs** [comment]
your example also shows the same behavior.

**Comment by hamishgibbs** [comment]
Now I understand - thanks. Looks like it is not throwing an error so must be something incorrect in the way that date filtering works. I will look into what is going on.
