### ISSUE TITLE
Button Placement

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/rt_vis#61]
Odd button positioning as if buttons are again being styled absolutely relative to screen width, not in place as they should be. 

@seabbs are you seeing similar issues on large monitors?

**Comment by hamishgibbs** [comment]
Download button: 

![Screenshot 2020-10-12 at 09 58 57](https://user-images.githubusercontent.com/50525951/95754857-a4c2ce00-0c71-11eb-9cb2-2318ff203e9a.png)

And source selection:

![Screenshot 2020-10-12 at 09 59 56](https://user-images.githubusercontent.com/50525951/95754880-b0ae9000-0c71-11eb-9070-62889b04ea75.png)

**Comment by seabbs** [comment]
yes I am :(

**Comment by hamishgibbs** [comment]
Oh dear - how long has it been going on?

**Comment by seabbs** [comment]
hmmm a while - didn't think it was a major issue I think. Not ideal though obviously.

**Comment by hamishgibbs** [comment]
I am quite sensitive about the position of these buttons. Working on fixing it now.

**Comment by hamishgibbs** [comment]
Looks like they are in place.

![Screenshot 2020-10-13 at 10 49 48](https://user-images.githubusercontent.com/50525951/95877265-eb7ff900-0d41-11eb-98fa-798595ae7a4b.png)
