### ISSUE TITLE
reported death data

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#8]
In updated vis (which looks pretty good on my phone) reported cases are shown for both cases and deaths
 This should probably also be switched.

Being able to switch between datasets is a really nice feature though. My one though is that perhaps this should be user supplied list and not hard coded as you can make RTS on basically anything!

**Comment by hamishgibbs** [comment]
Should be fixed. rtData will now be passed in json format `{'Source':{'rtData':x, 'casesInfectionData':x, 'casesReportData':x}, ...}`, and the data sources can be selected from a dropdown that appears when n sources > 1

**Comment by hamishgibbs** [comment]
Resolving promises in the JSON format recursively has made the page load slightly slower, ~1-1.5 seconds? but this will not effect the R package
