### ISSUE TITLE
Constraining forecast uncertainty. 

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#9]
Our estimates are often highly uncertain (too much so - this is an area of further work). Plotting all of the tails of this uncertainty may be unhelpful. In our static plots we limit uncertainty shown by a scaling that is 10* max reported cases which whilst a hack does the job. 

It might be a good idea to do something similar here. Either by with an option to switch off or baked in.

**Comment by hamishgibbs** [comment]
This was implemented previously but the behaviour was being overridden by the recent changes to improve flexibilty of the input datasets. 

The threshold should now be in place (see Chad or Zambia). If a `Cases by date of infection` estimate is > 10*max reported cases, all datasets are truncated to the date where max reported cases exceeded the threshold. 

Is this the correct approach?

**Comment by seabbs** [comment]
so there I am seeing that the number of days is being dropped entirely and not truncated? The implementation we have is to crop/truncate the CI but still show the estimate.

**Comment by hamishgibbs** [comment]
I now understand. When a value is greater than the maximum reported cases * 10, those values will now equal maximum reported cases * 10, not be dropped. 

Here is an example:

![Screenshot 2020-08-28 at 12 41 31](https://user-images.githubusercontent.com/50525951/91557306-28c42f00-e92c-11ea-833c-890ded212b0a.png)

**Comment by seabbs** [comment]
spot on.
